services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      # 在 Docker 內部，主機名稱就是服務名稱 "mongodb"
      - MONGO_URI=mongodb://mongodb:27017/login-system
    depends_on:
      - mongodb # 確保資料庫先啟動，後端再啟動

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
