import type { Metadata } from 'next'
import { Sansation } from 'next/font/google'
import './globals.css'

const sansation = Sansation({
  variable: '--font-sansation',
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sansation.variable}  antialiased`}>{children}</body>
    </html>
  )
}
